### ISSUE TITLE
Simplify environment settings

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-template#7]
The readme states a set of environment variables that should be overridden, which can be simplified or removed.

**Comment by chindris** [comment]
Hi @pmelab !
Do you already have an idea for simplifying this? It would be great to even find a way to remove them, but not sure yet how we could do that.

**Comment by pmelab** [comment]
* The `PROJECT_NAME` is already almost gone. The cms app can be called `@custom/cms`, and some other cases could be derived from the lagoon environment.
* The netlify settings should also be controlled by lagoon. If the lagoon env variable is not there, we assume the environment has not attached entlify app.
* The hash salt could be a hardcoded one that can be overridden via lagoon env variable.

The only case where adjustment is necessary is the project name in `.lagoon.yml` i think? In the other cases we should be able to achieve a state where it "works" out of the box, and we add environment variables to e.g. connect a specific lagoon environment to netlify.
